# -*- mode: ruby -*-
# vim: ft=ruby
VAGRANT_API_VERSION = '2'

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.box = 'ubuntu/trusty64'

  config.vm.define "comp" do |node|
    node.vm.provision :itamae do |itamae|
      itamae.sudo = true
      itamae.recipes = %w[itamae/default.rb]
      if ENV['CPU_ONLY']
        itamae.yaml = "itamae/cpu_node.yaml"
      else
        itamae.yaml = "itamae/gpu_node.yaml"
      end
    end
  end

  config.vm.provider :virtualbox do |vbox|
    vbox.cpus = 4
    vbox.memory = 2048
  end

  config.vm.provider :aws do |aws, override|
    aws.access_key_id     = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    aws.use_iam_profile   = ENV['AWS_ACCESS_KEY_ID'].nil?
    aws.keypair_name      = 'vagrant'
    aws.ami               = 'ami-20b6aa21' # Ubuntu 14.04
    aws.instance_type     = ENV['AWS_INSTANCE_TYPE'] || 'm3.medium'
    aws.region            = ENV['AWS_REGION'] || 'ap-northeast-1'
    aws.subnet_id         = ENV['AWS_SUBNET_ID']
    aws.security_groups   = ENV['AWS_SECURITY_GROUPS'].split(/\s+/)
    aws.tags = {
      'Name' => "computing-#{ENV['INSTANCE_NUMBER'] || '000'}",
      'Role' => 'computing',
    }

    aws.region_config 'ap-northeast-1' do |region|
      region.spot_instance  = true
      region.spot_max_price = '0.060'
    end

    override.vm.box = 'dummy'
    override.vm.box_url = 'https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box'

    override.ssh.username = 'ubuntu'
    # override.ssh.private_key_path = ''
  end
end
