# -*- mode: ruby -*-
# vim: ft=ruby
VAGRANT_API_VERSION = '2'

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.box = 'ubuntu/trusty64'

  config.vm.define "comp" do |node|
    node.vm.provision :itamae do |itamae|
      itamae.sudo = true
      itamae.recipes = %w[itamae/default.rb]
      if ENV['CPU_ONLY']
        itamae.yaml = "itamae/cpu_node.yaml"
      else
        itamae.yaml = "itamae/gpu_node.yaml"
      end
    end
  end

  config.vm.provider :virtualbox do |vbox|
    vbox.cpus = ENV['CPU'] || 4
    vbox.memory = ENV['MEM'] || 2048
  end
end
